### PR TITLE
ci: add workflow to check for thin-edge.io updates and create a PR

### PR DESCRIPTION
**Pull request by reubenmiller**
Add a workflow which runs daily (or on demain) to check if there are any new thin-edge.io versions and will create/update the BB file and create a PR.

The functionality is provided in a new `admin.sh` script which uses cloudsmith api to check the latest version and updates the checksums. The workflow will rely on git change detection to see if a PR needs to be raised or not.

### CODE REVIEW

**Review by Ruadhri17 — COMMENTED** [review]
@reubenmiller  just one question: will the workflow execute the `admin.sh` properly, if we are missing `python-setup` step?

**Comment by reubenmiller** [comment]
> @reubenmiller just one question: will the workflow execute the `admin.sh` properly, if we are missing `python-setup` step?

true, though if we are relying on the cloud hosted runner then we technically don't have to setup python up as it comes with python out of the box.

**Comment by reubenmiller** [comment]
Though I'm testing the workflow with `act` now...I push have to push some fixes

**Comment by reubenmiller** [comment]
I've sorted out a few problems, however I can't test the pushing of the new branch (for the PR creation), as this step is not working without `act` for some unknown reasons...so we might have to test that part out live.

**Review by Ruadhri17 — APPROVED** [review]

**Pull request merged**
